# Generated by Django 2.2.8 on 2019-12-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(help_text='Nombre para la credencial de acceso', max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(blank=True, help_text='URL del sitio (Opcional)', max_length=100, verbose_name='URL')),
                ('email', models.EmailField(blank=True, help_text='Opcional', max_length=100, verbose_name='Correo electrónico')),
                ('username', models.CharField(help_text='Usuario del sistema', max_length=100, verbose_name='Usuario')),
                ('password', models.CharField(help_text='Contraseña del sistema', max_length=100, verbose_name='Contraseña')),
                ('pin', models.IntegerField(blank=True, help_text='Opcional', verbose_name='PIN')),
                ('category', models.ForeignKey(help_text='Categoría de la credencial de acceso', on_delete=django.db.models.deletion.CASCADE, to='structure.Category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Credencial de Acceso',
                'verbose_name_plural': 'Credenciales de Acceso',
            },
        ),
    ]
