# Generated by Django 2.2.8 on 2019-12-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20191226_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscredential',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría de la credencial de acceso', null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Category', verbose_name='Categoria'),
        ),
    ]
